# Generated by Django 4.2.16 on 2025-10-03 06:58

# Django
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mumbleverse", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mumbleverseserver",
            name="mumble_virtual_server_id",
            field=models.IntegerField(default=1),
        ),
    ]
