# Generated by Django 4.2.16 on 2025-10-04 02:10

# Django
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eveonline", "0017_alliance_and_corp_names_are_not_unique"),
        ("authentication", "0024_alter_userprofile_language"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("mumbleverse", "0002_mumbleverseserver_mumble_virtual_server_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="mumbleverseserver",
            name="alliance_access",
            field=models.ManyToManyField(
                blank=True,
                help_text="Alliances to whose members this server is available.",
                to="eveonline.eveallianceinfo",
            ),
        ),
        migrations.AddField(
            model_name="mumbleverseserver",
            name="character_access",
            field=models.ManyToManyField(
                blank=True,
                help_text="Characters to which this server is available.",
                to="eveonline.evecharacter",
            ),
        ),
        migrations.AddField(
            model_name="mumbleverseserver",
            name="corporation_access",
            field=models.ManyToManyField(
                blank=True,
                help_text="Corporations to whose members this server is available.",
                to="eveonline.evecorporationinfo",
            ),
        ),
        migrations.AddField(
            model_name="mumbleverseserver",
            name="faction_access",
            field=models.ManyToManyField(
                blank=True,
                help_text="Factions to whose members this server is available.",
                to="eveonline.evefactioninfo",
            ),
        ),
        migrations.AddField(
            model_name="mumbleverseserver",
            name="group_access",
            field=models.ManyToManyField(
                blank=True,
                help_text="Groups to whose members this server is available.",
                to="auth.group",
            ),
        ),
        migrations.AddField(
            model_name="mumbleverseserver",
            name="state_access",
            field=models.ManyToManyField(
                blank=True,
                help_text="States to whose members this server is available.",
                to="authentication.state",
            ),
        ),
    ]
