# Generated by Django 4.2.16 on 2025-10-05 11:19

# Django
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mumbleverse", "0003_mumbleverseserver_alliance_access_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mumbleverseserveruser",
            name="uid",
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name="mumbleverseserveruser",
            name="username",
            field=models.CharField(max_length=254),
        ),
    ]
