# Generated by Django 4.2.16 on 2025-11-25 10:03

# Django
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mumbleverse", "0004_alter_mumbleverseserveruser_uid_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MumbleverseServerActiveFilter",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("description", models.CharField(max_length=500)),
                (
                    "reversed_logic",
                    models.BooleanField(
                        default=False,
                        help_text="If set all members WITHOUT an account will pass the test.",
                    ),
                ),
                (
                    "server",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mumbleverse.mumbleverseserver",
                    ),
                ),
            ],
            options={
                "verbose_name": "Smart Filter: Mumbleverse Server Active",
                "verbose_name_plural": "Smart Filter: Mumbleverse Server Active",
            },
        ),
    ]
